export const FIRST_ROUTE: string = '/'
export const BOOK_ROUTE: string = '/book/content'
export const VIDEO_ROUTE: string = '/book/videos'
export const PREZENTATIONS_ROUTE: string = '/book/prezentations'
export const CONSPECTS_ROUTE: string = '/book/abstract'
