export const FIRST_ROUTE: string = '/'
export const BOOK_ROUTE: string = '/book'
export const VIDEO_ROUTE: string = '/videos'
export const PREZENTATIONS_ROUTE: string = '/prezentations'
export const CONSPECTS_ROUTE: string = '/conspects'
